version: '3.8'

services:
  press:
    # 현재 디렉토리의 app 폴더를 빌드합니다.
    build: ./app
    # Django 애플리케이션을 실행하는 명령입니다.
    command: python manage.py runserver 0.0.0.0:8000
    # 호스트와 컨테이너 간의 파일 공유를 위한 볼륨 설정입니다.
    volumes:
      - ./app/:/usr/src/app/
    # 호스트와 컨테이너 간의 포트 포워딩 설정입니다.
    ports:
      - 8555:8000
    # 환경 변수 파일의 위치는 현재폴더의 app의 하위 .env.dev 폴더에 있다.
    env_file:
      - ./app/.env.dev
    # Django 애플리케이션을 실행하려면 데이터베이스가 먼저 준비되어 있어야 하기 때문에, press 서비스를 
    # 시작하기 전에 press_db 서비스가 시작되도록 보장
    depends_on:
      - press_db
  # PostgreSQL 데이터베이스 서비스 정의
  press_db:
    # PostgreSQL 16 이미지를 사용하여 데이터베이스를 실행합니다.
    image: postgres:16
    # 데이터베이스 데이터를 저장하기 위한 볼륨 설정입니다.
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # PostgreSQL 환경 변수 설정입니다.
    environment:
      # 데이터베이스 사용자 이름 설정
      - POSTGRES_USER=de
      # 데이터베이스 비밀번호 설정
      - POSTGRES_PASSWORD=1234
      # 데이터베이스 이름 설정
      - POSTGRES_DB=press_dev
# 볼륨 정의: PostgreSQL 데이터를 저장하기 위한 볼륨입니다.
volumes:
  postgres_data: